### ISSUE TITLE
Add test checking if all notebooks execute without an error

### ISSUE THREAD

**Issue by pat-schmitt** [OGGM/tutorials#86]
I just came across how to test jupyter notebooks https://www.blog.pythonlibrary.org/2018/10/16/testing-jupyter-notebooks/.

Maybe adding a simple test just checking if all tutorials pass without an error is a good idea?
But maybe it is overkill...

**Comment by fmaussion** [comment]
The book build allows errors on build:

```
execute:
  execute_notebooks: auto
  timeout: -1
  allow_errors: true
```

We could set this to false and see what happens...
